// נתוני יצרן בלבד (דף מוצר / TDS), נבדקו 19.9.2026. null = היצרן לא מפרסם. verified: true רק אחרי שהדפסתי עם זה בעצמי.
// ready: bs = שם פרופיל מובנה ב-Bambu Studio · orca = קיים בספריית OrcaSlicer · url = הורדה רשמית מהיצרן
const ESUN_DL = "https://www.esun3d.com/parameters-download", POLY_DL = "https://presets.polymaker.com";
const FILAMENTS = [
  { brand: "eSUN", line: "PLA+", mat: "PLA", nozzle: [210, 230], bed: [45, 60], speed: 300, fan: "100%", dry: "50°C, 8–12 שעות", enclosure: false, note: "", ready: { bs: "eSUN PLA+", url: ESUN_DL }, src: "https://www.esun3d.com/pla-pro-product" },
  { brand: "eSUN", line: "PLA-Basic", mat: "PLA", nozzle: [210, 230], bed: [45, 60], speed: 300, fan: "100%", dry: "50°C, 8–12 שעות", enclosure: false, note: "היצרן מצהיר על תאימות ל-AMS.", ready: { orca: true, url: ESUN_DL }, src: "https://www.esun3d.com/pla-basic-product" },
  { brand: "eSUN", line: "PLA-Matte (ePLA-Matte)", mat: "PLA", nozzle: [190, 230], bed: [45, 60], speed: 200, fan: "100%", dry: null, enclosure: false, note: "חומר רך — לא להדק את האקסטרודר חזק. בחום (מעל 32°C בחדר) סיכון לסתימה; במדפסת סגורה להשאיר דלת פתוחה.", ready: { orca: true, url: ESUN_DL }, src: "https://www.esun3d.com/epla-matte-product" },
  { brand: "eSUN", line: "PLA-Silk (eSilk-PLA)", mat: "PLA", nozzle: [190, 230], bed: [45, 60], speed: 200, fan: "100%", dry: null, enclosure: false, note: "לברק מקסימלי — להאט את הדופן החיצונית. במדפסת סגורה להשאיר דלת פתוחה.", ready: { url: ESUN_DL }, src: "https://www.esun3d.com/esilk-pla-product" },
  { brand: "eSUN", line: "ePLA-HS / PLA+HS", mat: "PLA", nozzle: [210, 230], bed: [45, 60], speed: 350, fan: "100%", dry: null, enclosure: false, note: "גרסת High-Speed.", ready: { url: ESUN_DL }, src: "https://www.esun3d.com/epla-hs-product" },
  { brand: "eSUN", line: "PETG", mat: "PETG", nozzle: [240, 260], bed: [75, 90], speed: 150, fan: "100%", dry: "60°C, 8 שעות ומעלה", enclosure: false, note: "", ready: { orca: true, url: ESUN_DL }, src: "https://www.esun3d.com/petg-product" },
  { brand: "eSUN", line: "ABS+", mat: "ABS", nozzle: [230, 270], bed: [95, 110], speed: 200, fan: "0%", dry: null, enclosure: true, note: "", ready: { url: ESUN_DL }, src: "https://www.esun3d.com/abs-pro-product" },
  { brand: "eSUN", line: "ASA+ (לשעבר eASA)", mat: "ASA", nozzle: [250, 280], bed: [90, 110], speed: 250, fan: "0–30%", dry: null, enclosure: true, note: "", ready: { url: ESUN_DL }, src: "https://www.esun3d.com/asa-pro-product" },
  { brand: "eSUN", line: "eTPU-95A", mat: "TPU", nozzle: [220, 250], bed: [45, 60], speed: 100, fan: "100%", dry: "55°C, 4 שעות ומעלה", enclosure: false, note: "Direct drive, לאט. לא ל-AMS.", ready: { url: ESUN_DL }, src: "https://www.esun3d.com/etpu-95a-product" },
  { brand: "SUNLU", line: "PLA", mat: "PLA", nozzle: [200, 240], bed: [50, 60], speed: 200, fan: null, dry: "50°C (היצרן לא מציין זמן)", enclosure: false, note: "200–210°C עד 100 מ\"מ/ש; 210–240°C במהירות גבוהה יותר.", ready: {}, src: "https://store.sunlu.com/products/over-6kg-of-pla-pla-meta-3d-filaments-1kg-2-2lbs-fit-most-of-fdm-printer" },
  { brand: "SUNLU", line: "PLA+", mat: "PLA", nozzle: [205, 245], bed: [50, 60], speed: 200, fan: null, dry: "50°C (היצרן לא מציין זמן)", enclosure: false, note: "205–215°C עד 100 מ\"מ/ש; 215–245°C במהירות גבוהה יותר.", ready: { bs: "SUNLU PLA+" }, src: "https://store.sunlu.com/products/over-6kg-bundle-sale-pla-and-pla-plus-pla-meta-macaron-filament1kg-roll" },
  { brand: "SUNLU", line: "PETG", mat: "PETG", nozzle: [240, 260], bed: [60, 70], speed: 300, fan: null, dry: "50°C (היצרן לא מציין זמן)", enclosure: false, note: "", ready: { bs: "SUNLU PETG" }, src: "https://store.sunlu.com/products/over-6kg-bundle-sale-petg-3d-printer-filament-1-75mm-1kg-roll" },
  { brand: "Polymaker", line: "PolyLite PLA", mat: "PLA", nozzle: [190, 230], bed: [25, 60], speed: 60, fan: "פועל", dry: "55°C, 6 שעות", enclosure: false, note: "תואם AMS.", ready: { bs: "PolyLite PLA", url: POLY_DL }, src: "https://shop.polymaker.com/products/polylite-pla" },
  { brand: "Polymaker", line: "Panchroma Matte PLA (לשעבר PolyTerra)", mat: "PLA", nozzle: [190, 230], bed: [25, 60], speed: 300, fan: "פועל", dry: "55°C, 6 שעות", enclosure: false, note: "מעט שוחק. תואם AMS.", ready: { bs: "PolyTerra PLA", url: POLY_DL }, src: "https://shop.polymaker.com/products/matte-pla" },
  { brand: "Polymaker", line: "Panchroma PLA", mat: "PLA", nozzle: [190, 230], bed: [25, 60], speed: 350, fan: "פועל", dry: "55°C, 6 שעות", enclosure: false, note: "תואם AMS.", ready: { orca: true, url: POLY_DL }, src: "https://shop.polymaker.com/products/panchroma-pla" },
  { brand: "Polymaker", line: "Polymaker PETG (לשעבר PolyLite PETG)", mat: "PETG", nozzle: [240, 260], bed: [60, 70], speed: 300, fan: "20–60%", dry: "60°C, 6 שעות", enclosure: false, note: "סופג לחות מהר מאוד.", ready: { bs: "PolyLite PETG", url: POLY_DL }, src: "https://shop.polymaker.com/products/petg" },
  { brand: "Polymaker", line: "Polymaker ASA (לשעבר PolyLite ASA)", mat: "ASA", nozzle: [240, 260], bed: [75, 95], speed: 200, fan: "כבוי", dry: "70°C, 6 שעות", enclosure: true, note: "", ready: { bs: "PolyLite ASA", url: POLY_DL }, src: "https://shop.polymaker.com/products/asa" },
  { brand: "Elegoo", line: "PLA", mat: "PLA", nozzle: [190, 230], bed: [35, 65], speed: 300, fan: null, dry: "50°C, 8 שעות", enclosure: false, note: "סליל קרטון — ב-AMS לשים לב לחיכוך.", ready: { orca: true }, src: "https://us.elegoo.com/products/pla-filament-1-75mm-colored-1kg" },
  { brand: "Elegoo", line: "PLA+", mat: "PLA", nozzle: [200, 230], bed: [35, 65], speed: 280, fan: null, dry: "50°C, 8 שעות", enclosure: false, note: "", ready: { orca: true }, src: "https://us.elegoo.com/products/elegoo-pla-plus-3d-printer-filament-1-75mm-colored-1kg" },
  { brand: "Elegoo", line: "Rapid PETG", mat: "PETG", nozzle: [240, 270], bed: [65, 75], speed: 600, fan: null, dry: "60°C, 8 שעות — היצרן מגדיר ייבוש כחובה", enclosure: false, note: "היצרן ממליץ על דבק למשטח.", ready: { orca: true }, src: "https://us.elegoo.com/products/rapid-petg-filament-1-75mm-colored-1kg" },
  { brand: "Creality", line: "CR-PETG", mat: "PETG", nozzle: [230, 250], bed: [60, 100], speed: 80, fan: "50–100%", dry: "60–65°C, 4–6 שעות", enclosure: false, note: "היצרן ממליץ להתחיל מ-240°C דיזה / 80°C משטח.", ready: { orca: true }, src: "https://wiki.creality.com/en/3d-printer-accessories/CR-PETG" },
  // ProFilament: מותג שמשווק בארץ ע"י ProMaker (כפר סבא). אין גיליון נתונים של יצרן — הנתונים מדף המוצר של המשווק (seller).
  { brand: "ProFilament", line: "PLA+ (PLA Pro)", mat: "PLA", nozzle: [190, 220], bed: null, speed: null, fan: null, dry: "אחסון עם סופחי לחות (המשווק לא מפרט ייבוש)", enclosure: false, note: "חומר הגלם של NatureWorks (ארה\"ב) לפי המשווק. ₪99, במבצע ₪84.", ready: {}, seller: "ProMaker", src: "https://promaker.co.il/product/%D7%92%D7%9C%D7%99%D7%9C-%D7%A4%D7%99%D7%9C%D7%9E%D7%A0%D7%98-%D7%9E%D7%A1%D7%95%D7%92-pla-pro-%D7%9E%D7%AA%D7%95%D7%A6%D7%A8%D7%AA-profilament-%D7%91%D7%90%D7%99%D7%9B%D7%95%D7%AA-%D7%94%D7%98-4/" },
  { brand: "ProFilament", line: "EZ PETG", mat: "PETG", nozzle: [220, 250], bed: [50, 70], speed: null, fan: "100%", dry: null, enclosure: false, note: "לפי המשווק: קל להדפסה יותר מ-PETG רגיל. ₪99.", ready: {}, seller: "ProMaker", src: "https://promaker.co.il/product/%D7%92%D7%9C%D7%99%D7%9C-%D7%A4%D7%99%D7%9C%D7%9E%D7%A0%D7%98-%D7%9E%D7%A1%D7%95%D7%92-ez-petg-%D7%9E%D7%AA%D7%95%D7%A6%D7%A8%D7%AA-profilament-%D7%91%D7%90%D7%99%D7%9B%D7%95%D7%AA-%D7%94%D7%98%D7%95/" },
  { brand: "Bambu Lab", line: "PLA Basic", mat: "PLA", nozzle: [190, 230], bed: [35, 45], speed: 300, fan: "פועל", dry: "50°C, 8 שעות", enclosure: false, note: "", ready: { bs: "Bambu PLA Basic" }, src: "https://store.bblcdn.com/s1/default/58b85d0f3db94878854a28fdb8a0006e/Bambu_PLA_Basic_Technical_Data_Sheet.pdf" },
  { brand: "Bambu Lab", line: "PLA Matte", mat: "PLA", nozzle: [190, 230], bed: [35, 45], speed: 300, fan: "פועל", dry: "50°C, 8 שעות", enclosure: false, note: "", ready: { bs: "Bambu PLA Matte" }, src: "https://store.bblcdn.com/s7/default/5b061f2feeac4ba88f355a33248bbda7/Bambu_PLA_Matte_Technical_Data_Sheet.pdf" },
  { brand: "Bambu Lab", line: "PETG HF", mat: "PETG", nozzle: [230, 260], bed: [65, 75], speed: 300, fan: "0–60%", dry: "65°C, 8 שעות", enclosure: false, note: "", ready: { bs: "Bambu PETG HF" }, src: "https://store.bblcdn.com/3a230e260a3a47c2b0db0156e07eef91.pdf" },
  { brand: "Bambu Lab", line: "ABS", mat: "ABS", nozzle: [240, 270], bed: [80, 100], speed: 300, fan: "0–80%", dry: "80°C, 8 שעות", enclosure: true, note: "טמפ' תא מומלצת 45–60°C.", ready: { bs: "Bambu ABS" }, src: "https://store.bblcdn.com/s7/default/23b4cf2b83d5470bb96d19970b5f3ae8/Bambu_ABS_Technical_Data_Sheet_V3.pdf" },
  { brand: "Bambu Lab", line: "ASA", mat: "ASA", nozzle: [240, 270], bed: [80, 100], speed: 250, fan: "0–80%", dry: "80°C, 8 שעות", enclosure: true, note: "טמפ' תא מומלצת 45–60°C.", ready: { bs: "Bambu ASA" }, src: "https://store.bblcdn.com/ad7b08230c164e72856cffbe06bb7dc9.pdf" },
  { brand: "Bambu Lab", line: "TPU for AMS", mat: "TPU", nozzle: [220, 240], bed: [30, 35], speed: 250, fan: "פועל", dry: "70°C, 8 שעות", enclosure: false, note: "דיזות 0.4/0.6/0.8 בלבד.", ready: { bs: "Bambu TPU for AMS" }, src: "https://store.bblcdn.com/s5/default/0a98353dce6d486ca848b21d2b19a207.pdf" },
];

// פרופילי Generic של Bambu Studio 2.8 שהפרופיל שנוצר יורש מהם: [שם האב, אורך מערך טמפ' הדיזה]. חומר שחסר = אין פרופיל כזה למדפסת.
const BBL_VERSION = "2.8.0.6";
const BBL_PARENTS = {"A1 mini": {"PLA": ["Generic PLA @BBL A1M", 1], "PETG": ["Generic PETG @BBL A1M", 1], "TPU": ["Generic TPU @BBL A1M", 1]}, "A1": {"PLA": ["Generic PLA @BBL A1", 1], "PETG": ["Generic PETG @BBL A1", 1], "ABS": ["Generic ABS @BBL A1", 1], "ASA": ["Generic ASA @BBL A1", 1], "TPU": ["Generic TPU @BBL A1", 1]}, "A2L": {"PLA": ["Generic PLA @BBL A2L", 1], "PETG": ["Generic PETG @BBL A2L", 1], "TPU": ["Generic TPU @BBL A2L", 1]}, "P1P / P1S": {"PLA": ["Generic PLA @BBL P1P", 2], "PETG": ["Generic PETG @BBL P1P", 2], "ABS": ["Generic ABS @BBL P1P", 2], "ASA": ["Generic ASA @BBL P1P", 2], "TPU": ["Generic TPU @BBL P1P", 2]}, "P2S": {"PLA": ["Generic PLA @BBL P2S", 3], "PETG": ["Generic PETG @BBL P2S", 3], "ABS": ["Generic ABS @BBL P2S", 3], "ASA": ["Generic ASA @BBL P2S", 3], "TPU": ["Generic TPU @BBL P2S", 3]}, "X1 / X1C": {"PLA": ["Generic PLA", 1], "PETG": ["Generic PETG", 1], "ABS": ["Generic ABS", 1], "ASA": ["Generic ASA", 1], "TPU": ["Generic TPU", 1]}, "X2D": {"PLA": ["Generic PLA @BBL X2D 0.4 nozzle", 6], "PETG": ["Generic PETG @BBL X2D 0.4 nozzle", 6], "ABS": ["Generic ABS @BBL X2D 0.4 nozzle", 6], "ASA": ["Generic ASA @BBL X2D 0.4 nozzle", 6], "TPU": ["Generic TPU @BBL X2D 0.4 nozzle", 6]}, "H2S": {"PLA": ["Generic PLA @BBL H2S", 3], "PETG": ["Generic PETG @BBL H2S", 3], "ABS": ["Generic ABS @BBL H2S 0.4 nozzle", 3], "ASA": ["Generic ASA @BBL H2S 0.4 nozzle", 3], "TPU": ["Generic TPU @BBL H2S", 3]}, "H2D": {"PLA": ["Generic PLA @BBL H2D", 3], "PETG": ["Generic PETG @BBL H2D", 3], "ABS": ["Generic ABS @BBL H2D", 3], "ASA": ["Generic ASA @BBL H2D", 3], "TPU": ["Generic TPU @BBL H2D", 4]}, "H2C": {"PLA": ["Generic PLA @BBL H2C 0.4 nozzle", 3], "PETG": ["Generic PETG @BBL H2C 0.4 nozzle", 3], "ABS": ["Generic ABS @BBL H2C 0.4 nozzle", 3], "ASA": ["Generic ASA @BBL H2C 0.4 nozzle", 3], "TPU": ["Generic TPU @BBL H2C 0.4 nozzle", 3]}};
