# Builds ../bbl-map.js from the locally installed Bambu Studio system profiles (names + array shapes only).
# Run after a Bambu Studio update:  python tools/build-bbl-map.py
import json, os, glob, re, collections

root = os.path.expandvars(r"%APPDATA%\BambuStudio\system")
load = lambda f: json.load(open(f, encoding="utf-8"))
fil = {}
for f in glob.glob(os.path.join(root, "BBL", "filament", "**", "*.json"), recursive=True):
    try: j = load(f); fil[j["name"]] = j
    except Exception: pass

# printers: machine model -> union of extruder variants (order kept), from the 0.4 nozzle machine preset
printers = {}
for f in glob.glob(os.path.join(root, "BBL", "machine", "*0.4 nozzle.json")):
    j = load(f); model = j["name"].replace(" 0.4 nozzle", "")
    variants = []
    for ext in j.get("extruder_variant_list") or []:
        for v in ext.split(","):
            if v not in variants: variants.append(v)
    printers[model] = variants  # [] = single-variant printer (A1 family)

def base_of(name):
    seen = set()
    while name in fil and name not in seen:
        seen.add(name)
        if name.endswith("@base"): return name
        name = fil[name].get("inherits") or ""
    return None

leaf_base, families = {}, collections.defaultdict(dict)
var_keys = collections.Counter()
for name, j in fil.items():
    cp = j.get("compatible_printers")
    if not cp: continue
    b = base_of(name)
    if not b: continue
    leaf_base[name] = b
    for p in cp:
        m = re.match(r"(.+) 0\.4 nozzle$", p)
        if m and m.group(1) in printers: families[b][m.group(1)] = name
    # keys that carry one value per extruder variant
    models = {re.sub(r" 0\.\d nozzle$", "", p) for p in cp}
    n = max((len(printers.get(m, [])) for m in models), default=0)
    if n > 1:
        for k, v in j.items():
            if isinstance(v, list) and len(v) == n and k != "compatible_printers": var_keys[k] += 1

ver = load(os.path.join(root, "BBL.json")).get("version")
out = {"version": ver, "printers": printers, "families": families, "leafBase": leaf_base,
       "variantKeys": sorted(k for k, c in var_keys.items() if c >= 3)}
dst = os.path.join(os.path.dirname(__file__), "..", "bbl-map.js")
open(dst, "w", encoding="utf-8").write("// generated by tools/build-bbl-map.py from Bambu Studio %s system profiles - names and shapes only\nconst BBL_MAP = %s;\nif (typeof module !== 'undefined') module.exports = BBL_MAP;\n" % (ver, json.dumps(out, ensure_ascii=False, separators=(",", ":"))))
print(ver, len(printers), "printers,", len(families), "families,", len(leaf_base), "leaves,", len(out["variantKeys"]), "variant keys")
print(out["variantKeys"])
